version: '3'

services:

  db:
    container_name: postgres_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=brilliant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main

  server:
    container_name: server
    build: ./server
    command: sh 'start_prod.sh'
    volumes:
      - static_volume:/app/static
      - /home/Brilliant/server/media:/app/media
    ports:
      - "8000:8000"
    networks:
      - main
  
    
volumes:
  static_volume:
  media_volume:



networks:
  main:
    driver: bridge