version: '3'

services:

  db:
    container_name: brilliant_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=brilliant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - brilliant

  server:
    container_name: brserver
    build: .
    command: sh 'start_prod.sh'
    volumes:
      - static_volume:/app/static
      - /home/Brilliant/media:/app/media
    ports:
      - "8000:8000"
    networks:
      - brilliant
    depends_on:
      - db
  
    
volumes:
  static_volume:
  media_volume:
  postgres_data:



networks:
  brilliant:
    driver: bridge