# Generated by Django 4.2 on 2023-04-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introslide',
            name='intro',
        ),
        migrations.AddField(
            model_name='introslidecontent',
            name='intro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.introslide'),
            preserve_default=False,
        ),
    ]
