# Generated by Django 4.0.10 on 2023-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitcard',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='benefitcard',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='benefitcard',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='benefitcard',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentslide',
            name='title_ru',
            field=models.CharField(blank=True, default='Equipment Slide', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentslide',
            name='title_uz',
            field=models.CharField(blank=True, default='Equipment Slide', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentslidecontent',
            name='subtitle_ru',
            field=models.CharField(default='Комлектация для руллоных штор', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentslidecontent',
            name='subtitle_uz',
            field=models.CharField(default='Комлектация для руллоных штор', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentslidecontent',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='equipmentslidecontent',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='equipmentslidecontent',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentslidecontent',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introslide',
            name='title_ru',
            field=models.CharField(blank=True, default='Intro Slide', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introslide',
            name='title_uz',
            field=models.CharField(blank=True, default='Intro Slide', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introslidecontent',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introslidecontent',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topblindsslide',
            name='title_ru',
            field=models.CharField(blank=True, default='Top Blinds', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topblindsslide',
            name='title_uz',
            field=models.CharField(blank=True, default='Top Blinds', max_length=255, null=True),
        ),
    ]
