# Generated by Django 4.2 on 2023-04-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_introslide_intro_introslidecontent_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introslide',
            name='title',
            field=models.CharField(blank=True, default='Inro Slide', max_length=255, null=True),
        ),
    ]
