# Generated by Django 4.2 on 2023-04-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_benefitcards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BenefitCards',
            new_name='BenefitCard',
        ),
    ]
