# Generated by Django 4.2 on 2023-04-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_benefitcards_benefitcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Equipment Slide', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSlideContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('subtitle', models.CharField(default='Комлектация для руллоных штор', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipmentslide')),
            ],
        ),
    ]
