# Generated by Django 4.2 on 2023-04-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBlindsSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Top Blinds', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='introslide',
            name='title',
            field=models.CharField(blank=True, default='Intro Slide', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TopBlinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topblindsslide')),
            ],
        ),
    ]
