# Generated by Django 4.2 on 2023-04-16 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
