# Generated by Django 4.1.7 on 2023-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumOfStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.BigIntegerField()),
                ('clients', models.BigIntegerField()),
                ('products', models.BigIntegerField()),
            ],
        ),
    ]
