# Generated by Django 4.0.10 on 2023-04-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.BigIntegerField(default=32112),
            preserve_default=False,
        ),
    ]
