# Generated by Django 4.0.10 on 2023-04-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_message_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
    ]
