# Generated by Django 4.0.10 on 2023-04-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_message_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stickerId', models.BigIntegerField()),
            ],
        ),
    ]
