# Generated by Django 4.0.10 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_sticker_stickerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTgGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramId', models.CharField(default='-1001875684284', max_length=500)),
            ],
            options={
                'verbose_name': 'Telegram Group Id',
                'verbose_name_plural': 'Telegram Group Id',
            },
        ),
    ]
